from groq import Groq
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from dotenv import load_dotenv

import uuid
import json
import os
from datetime import datetime

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))
app = Flask(__name__)

limiter = Limiter(
    key_func=get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://"
)

AUDIT_LOG_FILE = "audit_log.json"


def detect_with_groq(text):
    prompt = f"""
Determine whether the following text is more likely AI-generated or human-written.

Respond with ONLY one word:

AI
or
Human

Text:
{text}
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
        max_tokens=5,
    )

    return response.choices[0].message.content.strip()


def stylometric_score(text):
    words = text.split()
    sentences = [s.strip() for s in text.replace("!", ".").replace("?", ".").split(".") if s.strip()]

    if not words or not sentences:
        return 0.50

    unique_words = len(set(word.lower().strip(".,!?;:") for word in words))
    type_token_ratio = unique_words / len(words)

    sentence_lengths = [len(sentence.split()) for sentence in sentences]
    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)

    if len(sentence_lengths) > 1:
        variance = sum((length - avg_sentence_length) ** 2 for length in sentence_lengths) / len(sentence_lengths)
    else:
        variance = 0

    punctuation_count = sum(1 for char in text if char in ",;:")
    punctuation_density = punctuation_count / max(len(words), 1)

    score = 0.50

    if type_token_ratio < 0.55:
        score += 0.20

    if variance < 6:
        score += 0.20

    if punctuation_density > 0.08:
        score += 0.10

    return round(min(max(score, 0.0), 1.0), 2)


def generate_transparency_label(attribution):
    if attribution == "likely_ai":
        return "Likely AI-Generated: Our system has high confidence that this content was generated with the assistance of artificial intelligence."
    elif attribution == "likely_human":
        return "Likely Human-Written: Our system has high confidence that this content was written by a human author."
    else:
        return "Uncertain Attribution: Our system could not confidently determine whether this content was written by a human or generated by AI. Additional review may be necessary."


def load_log():
    if not os.path.exists(AUDIT_LOG_FILE):
        return []
    with open(AUDIT_LOG_FILE, "r", encoding="utf-8") as file:
        return json.load(file)


def save_log(entries):
    with open(AUDIT_LOG_FILE, "w", encoding="utf-8") as file:
        json.dump(entries, file, indent=2)


def add_log_entry(entry):
    entries = load_log()
    entries.append(entry)
    save_log(entries)


@app.route("/")
def home():
    return jsonify({
        "message": "Provenance Guard API is running."
    })


@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()

    text = data.get("text")
    creator_id = data.get("creator_id")

    if not text or not creator_id:
        return jsonify({"error": "text and creator_id are required"}), 400

    content_id = str(uuid.uuid4())

    groq_result = detect_with_groq(text)

    if groq_result.lower() == "ai":
        llm_score = 0.85
    elif groq_result.lower() == "human":
        llm_score = 0.15
    else:
        llm_score = 0.50

    style_score = stylometric_score(text)
    confidence = round((llm_score + style_score) / 2, 2)

    if confidence >= 0.70:
        attribution = "likely_ai"
    elif confidence <= 0.39:
        attribution = "likely_human"
    else:
        attribution = "uncertain"

    label = generate_transparency_label(attribution)

    response = {
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": confidence,
        "signals": {
            "groq_result": groq_result,
            "llm_score": llm_score,
            "stylometric_score": style_score
        },
        "label": label,
        "status": "classified"
    }

    log_entry = {
        "timestamp": datetime.utcnow().isoformat(),
        "event_type": "submission",
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": style_score,
        "label": label,
        "status": "classified"
    }

    add_log_entry(log_entry)

    return jsonify(response)


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()

    content_id = data.get("content_id")
    creator_reasoning = data.get("creator_reasoning")

    if not content_id or not creator_reasoning:
        return jsonify({"error": "content_id and creator_reasoning are required"}), 400

    log_entry = {
        "timestamp": datetime.utcnow().isoformat(),
        "event_type": "appeal",
        "content_id": content_id,
        "creator_reasoning": creator_reasoning,
        "status": "under_review"
    }

    add_log_entry(log_entry)

    return jsonify({
        "message": "Appeal received.",
        "content_id": content_id,
        "status": "under_review"
    })


@app.route("/log")
def log():
    return jsonify({
        "entries": load_log()
    })


if __name__ == "__main__":
    app.run(debug=True)